/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
reset;
model NLP_vent_HP.mod;
data  NLP_vent_HP.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building data
---------------------------------------------------------------------------------------------------------------------------------------*/
data Buildings_data/moesbBC.dat;
data Buildings_data/moesbCO.dat;
data Buildings_data/moesbBP.dat;
data Buildings_data/moesbBS.dat;
data Buildings_data/moesbTCV.dat;
data Buildings_data/moesbIN.dat;
data Buildings_data/moesbGC.dat;
data Buildings_data/moesbCE.dat;
data Buildings_data/moesbODY.dat;
data Buildings_data/moesbMA.dat;
data Buildings_data/moesbGR.dat;
data Buildings_data/moesbME.dat;
data Buildings_data/moesbCM.dat;
data Buildings_data/moesbAA.dat;
data Buildings_data/moesbBI.dat;
data Buildings_data/moesbEL.dat;
data Buildings_data/moesbPO.dat;
data Buildings_data/moesbCRPP.dat;
data Buildings_data/moesbMX.dat;
data Buildings_data/moesbBM.dat;
data Buildings_data/moesbCH.dat;
data Buildings_data/moesbDIA.dat;
data Buildings_data/moesbPH.dat;
data Buildings_data/moesbAI.dat;


/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
/*option solver './snopt';*/
option solver snopt;
#option omit_zero_rows 1;
#option omit_zero_cols 1;
option presolve_eps 8.53e-15;

/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display TC;
display OPEX;
display CAPEX;

display Area_Vent;
display Qheating;
display Heat_Vent;
display Trelease;


display E;
display E_2;

display Text;
display Text_new;
display Tair_in;
display Trelease;
display Trelease_2;

display Qevap_2;
display Qcond_2;
display COP_2;
display TLMCond_2;
display TLMEvapHP_2;
display Cost_HP;

